// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvmmdfvdvagmrwpgsbuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2bW1kZnZkdmFnbXJ3cGdzYnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODM5MDMyMzAsImV4cCI6MjA5OTQ3OTIzMH0.IaWsJrnUhKifjLX6EjHPD4Fu7e5fdLjG-d3JeTEzFUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});